version: '3'
services:
  api:
    build:
      context: .
      dockerfile: "./api/Dockerfile-golang"
    volumes:
      - ./api:/go/src/github.com/gouser/api
    ports:
      - 8080:8080
    container_name: api
    command: >
      sh -c "go mod tidy && go run main.go"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: money-boys

  frontend:
      build:
        context: .
        dockerfile: "./frontend/Dockerfile-nodejs"
      volumes:
        - ./frontend:/usr/src/frontend
      command: >
        sh -c "yarn install && yarn start"
      ports:
        - "3000:3000"
      container_name: frontend
      depends_on:
        - api
      stdin_open: true

  mysql:
      image: mysql:5.7.22
      environment:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
          MYSQL_DATABASE: money-boys
      ports:
        - "3306:3306"
      container_name: mysql
      volumes:
        - ./db/data:/var/lib/mysql
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./db/sql:/docker-entrypoint-initdb.d

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mysql
          - PMA_USER=admin
          - PMA_PASSWORD=admin
      links:
          - mysql
      ports:
          - 8888:80
      volumes:
          - /sessions
      container_name: phpmyadmin