FROM golang:1.19

ENV SRC_DIR=/go/src/github.com/gouser/api
ENV GOBIN=/go/bin

RUN mkdir -p $SRC_DIR
WORKDIR $SRC_DIR
ADD ./api .

RUN go get github.com/go-sql-driver/mysql \
    && go get -u github.com/gin-gonic/gin \
    && go get github.com/gorilla/mux \
    && go get -u github.com/jinzhu/gorm \
    && go get github.com/gin-contrib/cors \
    && go get gopkg.in/ini.v1

CMD ["go","run","main.go"]
